project:
  type: book
  output-dir: docs

book:
  title: "Rで機械学習！"
  site-url: https://honoka-nakano.github.io/MachineLearningWithR/
  repo-url: https://github.com/Honoka-Nakano/MachineLearningWithR/
  repo-branch: main
  sidebar:
    style: 'docked'
    pinned: true
    search: true
  chapters:
    - index.qmd
    - part: '内容'
      chapters:
        - chapter4.qmd
        - chapter5.qmd
        - chapter6.qmd
        - chapter7.qmd
        - chapter8.qmd
        - chapter9.qmd
  page-footer:
    center: 'Copyright 2024, Keisuke Nakano'

format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: true
    grid: 
      sidebar-width: 300px
    code-line-numbers: true
    code-annotations: hover
